# 设置如下secret字段
"""
TEXT(学院专业班级信息)               例：林学院-林学(陶铸实验班)-2017林学(陶铸实验班)1班
DEPTID(未知id字段)                   例：141670
ADDRESS(详细地址)                   例：非常富贵
ADDTEXT(省-市-县/区)                 例：江西省-南昌市-高新区
CODE(盲猜邮编)                       例：360192
STUNUM(学号)                       例：20170101
USERNAME(姓名)                     例：小冯
PHONENUM(电话)                     例：...自己电话...
USERID(完美校园分配的用户id)         例：6274894
EMERGENCY(紧急联系人)               例：紧急人
EMERGENCYPHONE(紧急联系人电话)       例：23667712771
SCKEY(Server酱微信推送)
"""


# 相关参数设置即对应下面的数据输入
"""
python3 17wanxiao.py <<EOF
${{secrets.TEXT}}
${{secrets.DEPTID}}
${{secrets.ADDRESS}}
${{secrets.ADDTEXT}}
${{secrets.CODE}}
${{secrets.STUNUM}}
${{secrets.USERNAME}}
${{secrets.PHONENUM}}
${{secrets.USERID}}
${{secrets.EMERGENCY}}
${{secrets.EMERGENCYPHONE}}
${{secrets.SCKEY}}
EOF
"""
name: 17wanxiaoCheckin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 22,4,9 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: Pip
      run: |
        #pip3 install requests pycryptodome
        pip3 install requests -i
      https://pypi.tuna.tsinghua.edu.cn/simple
         
    - name: HealthyCheckIn
      run: |
        python3 17wanxiao.py <<EOF
        #${{secrets.USERNAME}}
        #${{secrets.PASSWORD}}
        ${{secrets.TEXT}}
        ${{secrets.DEPTID}}
        ${{secrets.ADDRESS}}
        ${{secrets.ADDTEXT}}
        ${{secrets.CODE}}
        ${{secrets.STUNUM}}
        ${{secrets.USERNAME}}
        ${{secrets.PHONENUM}}
        ${{secrets.USERID}}
        ${{secrets.EMERGENCY}}
        ${{secrets.EMERGENCYPHONE}}
        ${{secrets.SCKEY}}
        EOF
        
